#!/usr/bin/env python3
"""Daemon Generator — creates new daemon scripts from templates."""

import os
from pathlib import Path
from datetime import datetime, timezone

DAEMON_TEMPLATE = '''#!/usr/bin/env python3
"""
{daemon_name} — auto-generated by self_expansion_daemon.
Purpose: {purpose}
"""

import json, time, os, sys
from pathlib import Path

sys.path.insert(0, "{research_dir}")
sys.path.insert(0, "{research_dir}/scripts")

from daemon_base import DaemonBase
from shared_memory import get_context_for_daemon, update_daemon_state, log_event

class {class_name}(DaemonBase):
    def __init__(self):
        super().__init__("{daemon_name}")

    def run_once(self) -> bool:
        context = get_context_for_daemon("{daemon_name}")
        log_event("cycle_complete", "{daemon_name}", "Completed cycle")
        return True

def main():
    daemon = {class_name}()
    daemon.run(interval={interval})

if __name__ == "__main__":
    main()
'''

def generate_daemon(daemon_name, purpose, domain, interval=300):
    research_dir = os.environ.get("RESEARCH_DIR", "/Users/saiful/temuclaude/research")
    class_name = "".join(w.capitalize() for w in daemon_name.split("_")) + "Daemon"
    script = DAEMON_TEMPLATE.format(daemon_name=daemon_name, class_name=class_name,
        purpose=purpose, interval=interval, research_dir=research_dir)
    filepath = Path(research_dir) / f"{daemon_name}.py"
    filepath.write_text(script)
    return str(filepath)
