import { NextRequest, NextResponse } from 'next/server';
import { getOrCreateUserByEmailAsync } from '@/lib/db';
import { getAuthenticatedSupabaseUser } from '@/lib/supabase-server';
import { getWorkspaceProject, listWorkspaceFiles, recordWorkspaceEvent } from '@/lib/workspace';
import { requestHermesPlan } from '@/lib/hermes';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
type Context = { params: Promise<{ projectId: string }> };
export async function POST(req: NextRequest, context: Context) { try { const auth = await getAuthenticatedSupabaseUser(req); if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); const email = auth.user.email?.trim().toLowerCase(); if (!email) return NextResponse.json({ error: 'Authenticated user has no email address' }, { status: 400 }); const body = await req.json().catch(() => null) as { prompt?: unknown } | null; if (typeof body?.prompt !== 'string' || !body.prompt.trim() || body.prompt.length > 12_000) return NextResponse.json({ error: 'prompt must be a non-empty string under 12,000 characters.' }, { status: 400 }); const { projectId } = await context.params; const user = await getOrCreateUserByEmailAsync(email, String(auth.user.user_metadata?.full_name || email.split('@')[0])); const project = await getWorkspaceProject(user.id, projectId); if (!project) return NextResponse.json({ error: 'Project not found.' }, { status: 404 }); const files = await listWorkspaceFiles(user.id, projectId); const plan = await requestHermesPlan({ prompt: body.prompt.trim(), projectTitle: project.title, files: files.map(({ file_path, byte_size, content }) => ({ file_path, byte_size, content })) }); await recordWorkspaceEvent({ userId: user.id, projectId, eventType: 'workspace.analysis.created', summary: `Generated workspace analysis via ${plan.runtime}`, details: { model: plan.model || 'unknown', runtime: plan.runtime, files: files.length } }); return NextResponse.json({ plan, capabilities: { workspaceRead: true, planning: true, approvalRequests: true, previewDeployments: true, approvalsRequiredFor: ['file writes', 'commands', 'network access', 'GitHub', 'deployments'] } }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Workspace analysis is unavailable.' }, { status: 503 }); } }
