import { NextRequest, NextResponse } from 'next/server';
import { getOrCreateUserByEmailAsync } from '@/lib/db';
import { getAuthenticatedSupabaseUser } from '@/lib/supabase-server';
import { listWorkspaceActions, requestWorkspaceAction, type WorkspaceActionType } from '@/lib/workspace';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
type Context = { params: Promise<{ projectId: string }> };
async function user(req: NextRequest) { const auth = await getAuthenticatedSupabaseUser(req); if ('error' in auth) return auth; const email = auth.user.email?.trim().toLowerCase(); if (!email) return { error: 'Authenticated user has no email address', status: 400 } as const; return { user: await getOrCreateUserByEmailAsync(email, String(auth.user.user_metadata?.full_name || email.split('@')[0])) } as const; }
export async function GET(req: NextRequest, context: Context) { try { const auth = await user(req); if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); const { projectId } = await context.params; return NextResponse.json({ actions: await listWorkspaceActions(auth.user.id, projectId) }); } catch { return NextResponse.json({ error: 'Approval service is unavailable.' }, { status: 503 }); } }
export async function POST(req: NextRequest, context: Context) { try { const auth = await user(req); if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status }); const body = await req.json().catch(() => null) as { actionType?: unknown; payload?: unknown; expiresInSeconds?: unknown } | null; if (typeof body?.actionType !== 'string' || (body.payload !== undefined && (typeof body.payload !== 'object' || Array.isArray(body.payload)))) return NextResponse.json({ error: 'Invalid approval request.' }, { status: 400 }); const { projectId } = await context.params; const action = await requestWorkspaceAction({ userId: auth.user.id, projectId, actionType: body.actionType as WorkspaceActionType, payload: body.payload as Record<string, unknown> | undefined, expiresInSeconds: typeof body.expiresInSeconds === 'number' ? body.expiresInSeconds : undefined }); return NextResponse.json({ action }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Could not request approval.' }, { status: 400 }); } }
