"""
Temuclaude Media Multi-Judge Consensus

3 vision-capable LLMs score each generated image/video. Majority vote or
weighted average determines the winner.

Adapted from consistency.py's self-consistency voting pattern.

Judges:
  1. MiniMax M3 (best vision, IQ 44) — weight 1.0
  2. Gemini 3 Flash (multimodal, IQ 50) — weight 0.95
  3. Claude Sonnet 5 (frontier reasoning, IQ 53) — weight 0.90

Each judge scores 1-10 on 4 dimensions (USVA-adapted):
  - Prompt adherence (did it follow the prompt?)
  - Visual quality (composition, lighting, detail)
  - Text accuracy (if text was requested)
  - Artifact detection (hands, faces, geometry)

The weighted average across all judges determines the final score.
The highest-scoring output is the winner.
"""

import asyncio
import logging
import json
from typing import Optional

logger = logging.getLogger(__name__)

# Scoring dimensions (USVA-adapted: Understand, Solve, Verify, Answer)
SCORING_DIMENSIONS = [
    "prompt_adherence",  # Did the output match the prompt?
    "visual_quality",    # Composition, lighting, detail
    "text_accuracy",     # If text was requested, is it correct?
    "artifact_free",     # No visible defects (hands, faces, geometry)
]


def build_judge_prompt(prompt: str, task_type: str, image_url: str, model_name: str) -> list:
    """Build the message for a vision LLM to judge an image.

    The judge sees the image and the original prompt, then scores it.
    """
    system_prompt = """You are an expert image quality judge. You evaluate AI-generated images on 4 dimensions, scoring each from 1 to 10.

Scoring rubric:
- prompt_adherence (1-10): Does the image match the prompt? 10 = perfect match, 1 = completely wrong.
- visual_quality (1-10): Composition, lighting, color, detail. 10 = professional quality, 1 = poor.
- text_accuracy (1-10): If text was requested, is it spelled correctly and legible? If no text requested, score 10.
- artifact_free (1-10): No visible defects (broken hands, distorted faces, geometry errors). 10 = no artifacts, 1 = severe artifacts.

Return ONLY a JSON object with the 4 scores. No explanation, no preamble.
Example: {"prompt_adherence": 8, "visual_quality": 9, "text_accuracy": 10, "artifact_free": 7}"""

    user_prompt = f"""Original prompt: {prompt}
Task type: {task_type}
Image to evaluate (generated by {model_name}): {image_url}

Score this image on the 4 dimensions. Return ONLY the JSON object."""

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def build_video_judge_prompt(prompt: str, task_type: str, video_url: str, model_name: str) -> list:
    """Build the message for a vision LLM to judge a video.

    For videos, we add motion and audio dimensions.
    """
    system_prompt = """You are an expert video quality judge. You evaluate AI-generated videos on 6 dimensions, scoring each from 1 to 10.

Scoring rubric:
- prompt_adherence (1-10): Does the video match the prompt? 10 = perfect match.
- visual_quality (1-10): Composition, lighting, color, detail, motion smoothness.
- text_accuracy (1-10): If text was requested, is it correct? If no text, score 10.
- artifact_free (1-10): No visible defects (distorted faces, geometry errors, flickering).
- motion_quality (1-10): Natural, smooth motion. 10 = cinematic quality, 1 = janky.
- audio_quality (1-10): If audio present, is it synchronized and clear? If no audio needed, score 10.

Return ONLY a JSON object with the 6 scores. No explanation, no preamble.
Example: {"prompt_adherence": 8, "visual_quality": 9, "text_accuracy": 10, "artifact_free": 7, "motion_quality": 8, "audio_quality": 9}"""

    user_prompt = f"""Original prompt: {prompt}
Task type: {task_type}
Video to evaluate (generated by {model_name}): {video_url}

Score this video on the 6 dimensions. Return ONLY the JSON object."""

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def parse_judge_response(response: str, media_type: str = "image") -> dict:
    """Parse the judge's response into scores.

    Expected format: JSON with score dimensions.
    Falls back to regex parsing if JSON is malformed.
    """
    # Try JSON parse first
    try:
        # Find JSON object in response
        start = response.find("{")
        end = response.rfind("}") + 1
        if start >= 0 and end > start:
            json_str = response[start:end]
            scores = json.loads(json_str)
            # Validate scores
            for dim in SCORING_DIMENSIONS:
                if dim not in scores:
                    scores[dim] = 5  # default middle score
            if media_type == "video":
                for dim in ["motion_quality", "audio_quality"]:
                    if dim not in scores:
                        scores[dim] = 5
            # Clamp scores to 1-10
            for key in scores:
                try:
                    scores[key] = max(1, min(10, float(scores[key])))
                except (ValueError, TypeError):
                    scores[key] = 5.0
            return scores
    except (json.JSONDecodeError, ValueError):
        pass

    # Fallback: regex parsing
    scores = {}
    for dim in SCORING_DIMENSIONS + (["motion_quality", "audio_quality"] if media_type == "video" else []):
        pattern = rf"{dim}['\"]?\s*[:=]\s*['\"]?(\d+(?:\.\d+)?)"
        match = re.search(pattern, response, re.IGNORECASE)
        if match:
            try:
                scores[dim] = max(1, min(10, float(match.group(1))))
            except ValueError:
                scores[dim] = 5.0
        else:
            scores[dim] = 5.0

    return scores


import re  # needed for fallback parsing


def calculate_overall_score(scores: dict, media_type: str = "image") -> float:
    """Calculate overall score from dimension scores.

    Weighted average — prompt_adherence and artifact_free are weighted higher
    because they're the most important for user satisfaction.
    """
    if media_type == "video":
        weights = {
            "prompt_adherence": 0.25,
            "visual_quality": 0.20,
            "text_accuracy": 0.10,
            "artifact_free": 0.15,
            "motion_quality": 0.15,
            "audio_quality": 0.15,
        }
    else:
        weights = {
            "prompt_adherence": 0.30,
            "visual_quality": 0.25,
            "text_accuracy": 0.15,
            "artifact_free": 0.30,
        }

    total_weight = sum(weights.values())
    weighted_sum = sum(scores.get(dim, 5.0) * weight for dim, weight in weights.items())
    return weighted_sum / total_weight


class MediaJudge:
    """Multi-judge consensus for media evaluation.

    3 vision LLMs score each output. Weighted average determines the winner.
    """

    def __init__(self, call_llm_func=None):
        """
        Args:
            call_llm_func: Async function to call an LLM.
                Signature: async func(model: str, messages: list, max_tokens: int) -> str
                This is typically orchestrator.call_model_with_fallback
        """
        self.call_llm_func = call_llm_func
        from .models import JUDGE_POOL
        self.judges = JUDGE_POOL

    async def judge_single(
        self,
        judge_model: dict,
        prompt: str,
        task_type: str,
        output_url: str,
        model_name: str,
        media_type: str = "image",
    ) -> dict:
        """Judge a single output with a single judge.

        Returns dict with scores and overall_score.
        """
        if not self.call_llm_func:
            # Fallback: return neutral scores (5.0 across the board)
            scores = {dim: 5.0 for dim in SCORING_DIMENSIONS}
            if media_type == "video":
                scores["motion_quality"] = 5.0
                scores["audio_quality"] = 5.0
            scores["overall"] = 5.0
            scores["judge"] = judge_model["id"]
            return scores

        try:
            if media_type == "video":
                messages = build_video_judge_prompt(prompt, task_type, output_url, model_name)
            else:
                messages = build_judge_prompt(prompt, task_type, output_url, model_name)

            response = await self.call_llm_func(
                judge_model.get("openrouter_id", judge_model["id"]),
                messages,
                max_tokens=300,
                temperature=0.0,  # deterministic scoring
            )

            scores = parse_judge_response(response, media_type)
            scores["overall"] = calculate_overall_score(scores, media_type)
            scores["judge"] = judge_model["id"]
            scores["weight"] = judge_model.get("weight", 1.0)
            return scores

        except Exception as e:
            logger.warning(f"Judge {judge_model['id']} failed: {e}")
            scores = {dim: 5.0 for dim in SCORING_DIMENSIONS}
            if media_type == "video":
                scores["motion_quality"] = 5.0
                scores["audio_quality"] = 5.0
            scores["overall"] = 5.0
            scores["judge"] = judge_model["id"]
            scores["weight"] = judge_model.get("weight", 1.0)
            scores["error"] = str(e)
            return scores

    async def judge_output(
        self,
        prompt: str,
        task_type: str,
        output: dict,
        media_type: str = "image",
    ) -> dict:
        """Judge a single output with ALL judges (multi-judge consensus).

        Returns dict with:
          - 'model': which model generated this output
          - 'url': output URL
          - 'judge_scores': list of individual judge scores
          - 'consensus_score': weighted average of judge scores
        """
        model_name = output.get("model", "unknown")
        output_url = output.get("url", "")

        if not output_url:
            return {
                "model": model_name,
                "url": "",
                "judge_scores": [],
                "consensus_score": 0.0,
            }

        # Run all judges in parallel
        tasks = [
            self.judge_single(judge, prompt, task_type, output_url, model_name, media_type)
            for judge in self.judges
        ]
        judge_results = await asyncio.gather(*tasks, return_exceptions=True)

        # Process judge results
        judge_scores = []
        for i, result in enumerate(judge_results):
            if isinstance(result, Exception):
                logger.warning(f"Judge {self.judges[i]['id']} raised exception: {result}")
                # Use neutral score
                judge_scores.append({
                    "judge": self.judges[i]["id"],
                    "overall": 5.0,
                    "weight": self.judges[i].get("weight", 1.0),
                    "error": str(result),
                })
            else:
                judge_scores.append(result)

        # Calculate weighted consensus score
        total_weight = 0.0
        weighted_sum = 0.0
        for js in judge_scores:
            weight = js.get("weight", 1.0)
            weighted_sum += js.get("overall", 5.0) * weight
            total_weight += weight

        consensus_score = weighted_sum / total_weight if total_weight > 0 else 5.0

        return {
            "model": model_name,
            "url": output_url,
            "judge_scores": judge_scores,
            "consensus_score": round(consensus_score, 2),
        }

    async def judge_all(
        self,
        prompt: str,
        task_type: str,
        outputs: list,
        media_type: str = "image",
        use_batch: bool = True,
    ) -> dict:
        """Judge all outputs and determine the winner.

        Args:
            prompt: Original user prompt
            task_type: Classified task type
            outputs: List of {model, url} dicts from generator
            media_type: "image" or "video"
            use_batch: If True, use batch judging (1 LLM call per judge, all outputs at once)
                       If False, use individual judging (1 LLM call per output per judge)

        Batch judging is 5x cheaper: 3 LLM calls instead of 15 for 5 outputs × 3 judges.

        Returns:
            Dict with:
              - 'judged_outputs': List of judged outputs sorted by consensus_score (desc)
              - 'winner': The highest-scoring output
              - 'best_score': The winner's consensus score
              - 'all_scores': Dict of model_id → consensus_score
        """
        if not outputs:
            return {
                "judged_outputs": [],
                "winner": None,
                "best_score": 0.0,
                "all_scores": {},
            }

        # Check if batch judging is enabled
        from .models import BATCH_JUDGE_ENABLED
        if use_batch and BATCH_JUDGE_ENABLED and self.call_llm_func:
            return await self._judge_all_batch(prompt, task_type, outputs, media_type)

        # Fallback: individual judging (original approach)
        # Each output is judged by all judges — parallelized across outputs
        tasks = [
            self.judge_output(prompt, task_type, output, media_type)
            for output in outputs
        ]
        judged = await asyncio.gather(*tasks, return_exceptions=True)

        # Process results
        judged_outputs = []
        for i, result in enumerate(judged):
            if isinstance(result, Exception):
                logger.warning(f"Judging output {i} failed: {result}")
                judged_outputs.append({
                    "model": outputs[i].get("model", "unknown"),
                    "url": outputs[i].get("url", ""),
                    "judge_scores": [],
                    "consensus_score": 0.0,
                    "error": str(result),
                })
            else:
                judged_outputs.append(result)

        # Sort by consensus score (descending)
        judged_outputs.sort(key=lambda x: x.get("consensus_score", 0.0), reverse=True)

        # Build summary
        all_scores = {jo["model"]: jo.get("consensus_score", 0.0) for jo in judged_outputs}
        winner = judged_outputs[0] if judged_outputs else None
        best_score = winner.get("consensus_score", 0.0) if winner else 0.0

        return {
            "judged_outputs": judged_outputs,
            "winner": winner,
            "best_score": best_score,
            "all_scores": all_scores,
        }

    async def _judge_all_batch(
        self,
        prompt: str,
        task_type: str,
        outputs: list,
        media_type: str = "image",
    ) -> dict:
        """Batch judge all outputs — each judge scores ALL outputs in a single LLM call.

        This reduces LLM calls from N_outputs × N_judges to just N_judges.
        For 5 outputs × 3 judges: 15 calls → 3 calls (5x savings).

        The judge receives all image URLs at once and returns scores for each.
        """
        # Build the batch judge prompt with all outputs
        media_word = "video" if media_type == "video" else "image"

        if media_type == "video":
            system_prompt = """You are an expert video quality judge. You evaluate multiple AI-generated videos at once, scoring each on 6 dimensions (1-10).

Dimensions: prompt_adherence, visual_quality, text_accuracy, artifact_free, motion_quality, audio_quality

Return ONLY a JSON array where each element has a "model" field and the 6 score fields.
Example: [{"model": "model-a", "prompt_adherence": 8, "visual_quality": 9, "text_accuracy": 10, "artifact_free": 7, "motion_quality": 8, "audio_quality": 9}, {"model": "model-b", ...}]"""
        else:
            system_prompt = """You are an expert image quality judge. You evaluate multiple AI-generated images at once, scoring each on 4 dimensions (1-10).

Dimensions: prompt_adherence, visual_quality, text_accuracy, artifact_free

Return ONLY a JSON array where each element has a "model" field and the 4 score fields.
Example: [{"model": "model-a", "prompt_adherence": 8, "visual_quality": 9, "text_accuracy": 10, "artifact_free": 7}, {"model": "model-b", ...}]"""

        # Build the list of outputs for the judge
        output_list_text = "\n".join(
            f"{i+1}. Model: {output.get('model', 'unknown')} — URL: {output.get('url', '')}"
            for i, output in enumerate(outputs)
        )

        user_prompt = f"""Original prompt: {prompt}
Task type: {task_type}

Score EACH of these {len(outputs)} {media_word}s on all dimensions. Return a JSON array with one entry per {media_word}.

{media_word.capitalize()}s to evaluate:
{output_list_text}

Return ONLY the JSON array, no preamble."""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

        # Run each judge in parallel — but each judge gets ALL outputs at once
        judge_tasks = []
        for judge in self.judges:
            judge_tasks.append(self._batch_judge_single(judge, messages, outputs, media_type))

        batch_results = await asyncio.gather(*judge_tasks, return_exceptions=True)

        # Process batch results
        # Each batch_result is a dict: {model_id: {scores + overall}, ...}
        # We need to merge across judges (consensus)

        # Collect all model IDs
        model_ids = [o.get("model", "unknown") for o in outputs]

        # Build judged_outputs from batch results
        judged_outputs = []
        for model_id in model_ids:
            judge_scores_for_model = []
            total_weight = 0.0
            weighted_sum = 0.0

            for i, batch_result in enumerate(batch_results):
                judge = self.judges[i]
                if isinstance(batch_result, Exception):
                    logger.warning(f"Batch judge {judge['id']} failed: {batch_result}")
                    judge_scores_for_model.append({
                        "judge": judge["id"],
                        "overall": 5.0,
                        "weight": judge.get("weight", 1.0),
                        "error": str(batch_result),
                    })
                    weighted_sum += 5.0 * judge.get("weight", 1.0)
                    total_weight += judge.get("weight", 1.0)
                elif isinstance(batch_result, dict) and model_id in batch_result:
                    scores = batch_result[model_id]
                    judge_scores_for_model.append(scores)
                    weighted_sum += scores.get("overall", 5.0) * scores.get("weight", 1.0)
                    total_weight += scores.get("weight", 1.0)
                else:
                    judge_scores_for_model.append({
                        "judge": judge["id"],
                        "overall": 5.0,
                        "weight": judge.get("weight", 1.0),
                    })
                    weighted_sum += 5.0 * judge.get("weight", 1.0)
                    total_weight += judge.get("weight", 1.0)

            consensus_score = weighted_sum / total_weight if total_weight > 0 else 5.0

            # Find the URL for this model
            url = next((o.get("url", "") for o in outputs if o.get("model") == model_id), "")

            judged_outputs.append({
                "model": model_id,
                "url": url,
                "judge_scores": judge_scores_for_model,
                "consensus_score": round(consensus_score, 2),
            })

        # Sort by consensus score (descending)
        judged_outputs.sort(key=lambda x: x.get("consensus_score", 0.0), reverse=True)

        # Build summary
        all_scores = {jo["model"]: jo.get("consensus_score", 0.0) for jo in judged_outputs}
        winner = judged_outputs[0] if judged_outputs else None
        best_score = winner.get("consensus_score", 0.0) if winner else 0.0

        return {
            "judged_outputs": judged_outputs,
            "winner": winner,
            "best_score": best_score,
            "all_scores": all_scores,
            "batch_judge_used": True,
        }

    async def _batch_judge_single(
        self,
        judge: dict,
        messages: list,
        outputs: list,
        media_type: str = "image",
    ) -> dict:
        """Run a single judge on ALL outputs in one LLM call.

        Returns:
            Dict mapping model_id → {scores + overall + judge + weight}
        """
        try:
            response = await self.call_llm_func(
                judge.get("openrouter_id", judge["id"]),
                messages,
                max_tokens=2000,  # larger because we're scoring multiple outputs
                temperature=0.0,
            )

            # Parse the JSON array from the response
            import json
            result = {}

            try:
                # Find JSON array in response
                start = response.find("[")
                end = response.rfind("]") + 1
                if start >= 0 and end > start:
                    json_str = response[start:end]
                    scores_array = json.loads(json_str)

                    for entry in scores_array:
                        model_id = entry.get("model", "")
                        if not model_id:
                            continue

                        # Extract scores
                        scores = {}
                        for dim in SCORING_DIMENSIONS:
                            val = entry.get(dim, 5)
                            try:
                                scores[dim] = max(1, min(10, float(val)))
                            except (ValueError, TypeError):
                                scores[dim] = 5.0

                        if media_type == "video":
                            for dim in ["motion_quality", "audio_quality"]:
                                val = entry.get(dim, 5)
                                try:
                                    scores[dim] = max(1, min(10, float(val)))
                                except (ValueError, TypeError):
                                    scores[dim] = 5.0

                        scores["overall"] = calculate_overall_score(scores, media_type)
                        scores["judge"] = judge["id"]
                        scores["weight"] = judge.get("weight", 1.0)
                        result[model_id] = scores

            except (json.JSONDecodeError, ValueError) as e:
                logger.warning(f"Batch judge JSON parse failed for {judge['id']}: {e}")
                # Fallback: assign neutral scores to all models
                for output in outputs:
                    model_id = output.get("model", "unknown")
                    scores = {dim: 5.0 for dim in SCORING_DIMENSIONS}
                    if media_type == "video":
                        scores["motion_quality"] = 5.0
                        scores["audio_quality"] = 5.0
                    scores["overall"] = 5.0
                    scores["judge"] = judge["id"]
                    scores["weight"] = judge.get("weight", 1.0)
                    result[model_id] = scores

            return result

        except Exception as e:
            logger.warning(f"Batch judge {judge['id']} failed: {e}")
            # Return neutral scores for all models
            result = {}
            for output in outputs:
                model_id = output.get("model", "unknown")
                scores = {dim: 5.0 for dim in SCORING_DIMENSIONS}
                if media_type == "video":
                    scores["motion_quality"] = 5.0
                    scores["audio_quality"] = 5.0
                scores["overall"] = 5.0
                scores["judge"] = judge["id"]
                scores["weight"] = judge.get("weight", 1.0)
                scores["error"] = str(e)
                result[model_id] = scores
            return result