import { Navbar } from '@/components/Navbar';

const projects = [
  {
    name: 'SaaS Landing Page',
    category: 'Website',
    description: 'A complete, production-quality landing page with animated hero, glassmorphism feature cards, scroll reveals, pricing section, and testimonials carousel.',
    url: '/showcase/website.html',
    tokens: 8127,
    cost: '$0.0117',
    time: '118.8s',
    size: '23KB',
    accent: '#E25822',
  },
  {
    name: '2048 Game',
    category: 'Game',
    description: 'A polished 2048 game with smooth tile animations, keyboard and touch swipe controls, score tracking with localStorage, game over overlay, and win celebration.',
    url: '/showcase/game.html',
    tokens: 3668,
    cost: '$0.0053',
    time: '117.0s',
    size: '11KB',
    accent: '#788C5D',
  },
  {
    name: 'Interactive Solar System',
    category: 'Webpage',
    description: 'All 8 planets orbiting the sun with relative speeds, twinkling starfield, click planets for info, zoom and pan controls, orbit paths, and particle trails.',
    url: '/showcase/solar.html',
    tokens: 5145,
    cost: '$0.0074',
    time: '97.5s',
    size: '14KB',
    accent: '#C46686',
  },
  {
    name: 'Particle Galaxy',
    category: 'Animation',
    description: '1000+ particles forming a rotating spiral galaxy with warm center and cool edges. Mouse attraction, click explosions, glow effects, and FPS counter.',
    url: '/showcase/particles.html',
    tokens: 3830,
    cost: '$0.0055',
    time: '88.4s',
    size: '11KB',
    accent: '#E8B547',
  },
  {
    name: 'Agent Swarm',
    category: 'Agent System',
    description: 'A 3-agent research pipeline (Researcher, Analyzer, Writer) that collaborates to produce a full research report on AI orchestration. Built and executed via the API.',
    url: '/showcase/swarm.py',
    tokens: 2250,
    cost: '$0.0032',
    time: '82.8s',
    size: '8KB',
    accent: '#5D9CEC',
    runTokens: 8761,
    runCost: '$0.0126',
    runTime: '208.2s',
  },
];

const totalBuildTokens = 23020;
const totalBuildCost = '$0.0331';
const totalRunTokens = 8761;
const totalRunCost = '$0.0126';
const grandTotal = '$0.0457';

export default function ShowcasePage() {
  return (
    <>
      <Navbar />
      <main id="main-content" className="pt-24 pb-20 px-6" aria-label="Showcase">
        <div className="container-max">
          <h1 className="text-3xl md:text-4xl font-light text-text-primary mb-3" style={{ fontWeight: 300, letterSpacing: '-0.03em' }}>
            Built by TemuClaude
          </h1>
          <p className="text-text-secondary mb-8 max-w-2xl">
            Every project below was generated by a single API call to TemuClaude.
            No human wrote any of this code. The cost of each project is tracked
            in tokens and dollars — proving you can build production-quality software
            for pennies.
          </p>

          {/* Cost summary banner */}
          <div className="card mb-12" style={{ padding: '24px', background: 'linear-gradient(135deg, rgba(226,88,34,0.05) 0%, rgba(120,140,93,0.05) 100%)' }}>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
              <div>
                <div className="text-2xl font-serif text-text-primary" style={{ fontWeight: 300 }}>{totalBuildTokens.toLocaleString()}</div>
                <div className="text-xs text-text-muted mt-1">tokens to build all 5</div>
              </div>
              <div>
                <div className="text-2xl font-serif text-accent-primary" style={{ fontWeight: 300 }}>{totalBuildCost}</div>
                <div className="text-xs text-text-muted mt-1">cost to build all 5</div>
              </div>
              <div>
                <div className="text-2xl font-serif text-text-primary" style={{ fontWeight: 300 }}>{(totalBuildTokens + totalRunTokens).toLocaleString()}</div>
                <div className="text-xs text-text-muted mt-1">total tokens (build + run)</div>
              </div>
              <div>
                <div className="text-2xl font-serif text-accent-olive" style={{ fontWeight: 300 }}>{grandTotal}</div>
                <div className="text-xs text-text-muted mt-1">total cost (build + run)</div>
              </div>
            </div>
          </div>

          {/* Project cards */}
          <div className="grid md:grid-cols-2 gap-6 mb-12">
            {projects.map((project, i) => (
              <div key={i} className="card flex flex-col" style={{ padding: '24px' }}>
                <div className="flex items-center gap-2 mb-3">
                  <span className="badge-accent text-xs">{project.category}</span>
                </div>
                <h3 className="text-lg font-semibold text-text-primary mb-2">{project.name}</h3>
                <p className="text-sm text-text-secondary leading-relaxed mb-4 flex-1">{project.description}</p>

                <div className="grid grid-cols-3 gap-3 mb-4 text-center">
                  <div className="bg-bg-tertiary/40 rounded-sm py-2 px-1">
                    <div className="text-sm font-mono text-text-primary">{project.tokens.toLocaleString()}</div>
                    <div className="text-[10px] text-text-muted mt-0.5">tokens</div>
                  </div>
                  <div className="bg-bg-tertiary/40 rounded-sm py-2 px-1">
                    <div className="text-sm font-mono text-accent-primary">{project.cost}</div>
                    <div className="text-[10px] text-text-muted mt-0.5">cost</div>
                  </div>
                  <div className="bg-bg-tertiary/40 rounded-sm py-2 px-1">
                    <div className="text-sm font-mono text-text-primary">{project.time}</div>
                    <div className="text-[10px] text-text-muted mt-0.5">gen time</div>
                  </div>
                </div>

                {project.runTokens && (
                  <div className="mb-4 p-3 rounded-sm" style={{ background: 'rgba(93,156,236,0.05)', border: '1px solid rgba(93,156,236,0.15)' }}>
                    <div className="text-xs text-text-muted mb-1">After execution (3 agents collaborating):</div>
                    <div className="flex gap-4 text-xs font-mono">
                      <span className="text-text-primary">{project.runTokens.toLocaleString()} tokens</span>
                      <span className="text-accent-primary">{project.runCost}</span>
                      <span className="text-text-muted">{project.runTime}</span>
                    </div>
                  </div>
                )}

                <a
                  href={project.url}
                  target={project.url.endsWith('.html') ? '_blank' : undefined}
                  rel={project.url.endsWith('.html') ? 'noopener noreferrer' : undefined}
                  className="btn-secondary w-full justify-center"
                >
                  {project.url.endsWith('.html') ? 'View Live' : 'View Source'}
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
                </a>
              </div>
            ))}
          </div>

          {/* How this works */}
          <div className="max-w-2xl">
            <h2 className="text-xl font-semibold text-text-primary mb-4">How this works</h2>
            <div className="space-y-3 text-sm text-text-secondary">
              <p>
                <strong className="text-text-primary">1.</strong> A single prompt was sent to the TemuClaude API
                (<code className="text-xs bg-bg-tertiary px-1.5 py-0.5 rounded font-mono">POST /v1/chat/completions</code>)
                for each project. The API ran the full 8-model orchestration pipeline — classifying the task,
                routing to the best models, fusing their outputs, and quality-checking the result.
              </p>
              <p>
                <strong className="text-text-primary">2.</strong> The returned code was saved as-is — no edits,
                no cherry-picking. What you see is exactly what the API produced.
              </p>
              <p>
                <strong className="text-text-primary">3.</strong> Token counts and costs are from the actual API
                response <code className="text-xs bg-bg-tertiary px-1.5 py-0.5 rounded font-mono">usage</code> field.
                Cost is calculated at $1.44/M tokens (blended average).
              </p>
              <p>
                <strong className="text-text-primary">4.</strong> The agent swarm was then executed — 3 agents
                (Researcher, Analyzer, Writer) each made their own API calls, collaborating to produce a
                full research report on AI orchestration. That cost is tracked separately.
              </p>
            </div>
          </div>

          {/* CTA */}
          <div className="mt-12 text-center">
            <p className="text-sm text-text-muted mb-4">
              Total cost to build and run everything: <strong className="text-accent-primary">{grandTotal}</strong>.
              That's less than a single Claude API call.
            </p>
            <a href="/playground" className="btn-accent">
              Build something with TemuClaude
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
            </a>
          </div>
        </div>
      </main>
    </>
  );
}